/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface BookBody {
  title: string;
  author: string;
  realeaseYear: number;
  genre: "FICTION" | "NON_FICTION" | "DRAMA" | "THRILLER" | "SCI_FI" | "OTHERS";
  pages: number;
  isbn?: string;
  rating?: "ONE" | "TWO" | "THREE" | "FOUR" | "FIVE";
  user?: {
    [k: string]: unknown;
  };
}
