name: "NYC REPORTER"

on:
  push:
      branches: [ master ]
  pull_request:
    branches:
      - '*'

jobs:
  check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.15.0]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Packages
        run: npm install

      - uses: bahmutov/npm-install@v1

      - name: Run test Coverage
      - run: npm run test-coverage
      
      - uses: tintef/nyc-reporter-action@0.1.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPORTER: 'text'
