name: "NYC REPORTER"

on:
  push:
      branches: [ master ]
  pull_request:
    branches:
      - '*'

jobs:
  check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.15.0]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Packages
        run: npm install

      - uses: bahmutov/npm-install@v1


      - name: Report test coverage
        uses: PoorlyDefinedBehaviour/nyc-reporter@v1
        with:
          command: "npm run test-coverage"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}